### ISSUE TITLE
valueError: unkown file extension

### ISSUE THREAD

**Issue by zzinzziny** [harikc456/speech-bubble-extraction#1]
Hi.
Thank you for opening code.
While I run this code, it appears error messages.
What happens?
What can I do to solve this situations?

  File "/data/anaconda3/envs/imt_221125/lib/python3.8/site-packages/PIL/Image.py", line 2331, in save
    format = EXTENSION[ext]
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "easyocr_translate.py", line 76, in <module>
    im_pil.save(OUT_PATH)
  File "/data/anaconda3/envs/imt_221125/lib/python3.8/site-packages/PIL/Image.py", line 2333, in save
    raise ValueError(f"unknown file extension: {ext}") from e
ValueError: unknown file extension:

**Comment by harikc456** [comment]
Can you share how you are running the script?

**Comment by zzinzziny** [comment]
I'm running easyocr_translate.py with this script.

python easyocr_translate.py --img_path /home/ubuntu/speech-bubble-extraction/image_kor/kor_1.png --out_path /home/ubuntu/speech-bubble-extraction/

**Comment by harikc456** [comment]
Ok, thanks for the reply. Can you try running the same script with the output file name? Something like this
```
python easyocr_translate.py --img_path /home/ubuntu/speech-bubble-extraction/image_kor/kor_1.png --out_path /home/ubuntu/speech-bubble-extraction/output.png
```
